language: php

php:
  - 7.3
  - 7.4
  - 8.0

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest --prefer-dist"
  matrix:
    - PHPUNIT_VERSION=^7.0
    - PHPUNIT_VERSION=^8.0

matrix:
  include:
    - php: 7.3
      env: PHPUNIT_VERSION=^8.0 EXTRA_COMPOSER_FLAGS=--prefer-lowest
    - php: 7.4
      env: PHPUNIT_VERSION=^8.0 EXTRA_COMPOSER_FLAGS=--prefer-lowest

before_install: composer require phpunit/phpunit:$PHPUNIT_VERSION --no-update

install: composer update $DEFAULT_COMPOSER_FLAGS $EXTRA_COMPOSER_FLAGS

script: vendor/bin/phpunit tests

cache:
  directories:
    - $HOME/.composer/cache/files
