language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest --prefer-dist"
  matrix:
    - PHPUNIT_VERSION=7.0.x
    - PHPUNIT_VERSION=8.0.x
    - EXTRA_COMPOSER_FLAGS=--prefer-lowest

install: composer update $DEFAULT_COMPOSER_FLAGS $EXTRA_COMPOSER_FLAGS

script: vendor/bin/phpunit tests

cache:
  directories:
    - $HOME/.composer/cache/files
