name: Unit Tests

on:
    push:
        branches:
            - "*"
        pull_request:
            - "*"

jobs:
    unittest:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                # operating-system: [ubuntu-latest, windows-latest, macOS-latest]
                php:
                    - version: "7.4"
                      composer-args: ""
                    - version: "8.0"
                      composer-args: ""
                    - version: "8.1"
                      composer-args: "--ignore-platform-req=php"
                    - version: "8.2"
                      composer-args: "--ignore-platform-req=php"
                prefer-lowest: ["", "--prefer-lowest"]

        name: Unit Tests - PHP ${{ matrix.php.version }} ${{ matrix.prefer-lowest }}

        steps:
            - uses: actions/checkout@v2

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php.version }}
                  # extensions: intl #optional
                  # ini-values: "post_max_size=256M" #optional

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v2
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-

            - name: Install dependencies
              run: |
                  composer update \
                      --no-interaction --no-ansi --no-progress --no-suggest --prefer-dist \
                      ${{ matrix.prefer-lowest }} \
                      ${{ matrix.php.composer-args }}

            - name: Run test suite
              run: ./vendor/bin/phpunit tests
